import Cocoa

print("안녕하세요")
print("月火水")
print("  +---------------------------------+")
print(" /\t\t\t\t\t\t\t\t   /|")
print("+---------------------------------+ |")
print("|\t\t\t\t\t\t\t\t  | |")
print("|\t\t\t-\t\t-\t\t\t  | |")
print("|\t\t\t⦿\t\t⦿\t\t\t  | |")
print("|\t\t\t\t▽\t\t\t\t  | |")
print("|\t\t\t\t\t\t\t\t  | +")
print("|\t\t\t\t\t\t\t\t  |/")
print("+---------------------------------+ ")

print("  +---------------------------------+")
print(" /\t\t\t\t\t\t\t\t   /|")
print("+---------------------------------+ |")
print("|\t\t\t\t\t\t\t\t  | |")
print("|\t\t\t-\t\t-\t\t\t  | |")
print("|\t\t\t●\t\t●\t\t\t  | |")
print("|\t\t\t\t▼\t\t\t\t  | |")
print("|\t\t\t\t\t\t\t\t  | +")
print("|\t\t\t\t\t\t\t\t  |/")
print("+---------------------------------+")
